# wrangler.toml
name = "my-tech-blog"

# 重要: 出力ディレクトリを指定
pages_build_output_dir = ".next"

# トップページとその他のpage.tsxファイル用のルート設定
[routes]
"/" = { script = "app/page" }
"/*" = { script = "app" }
"/api/github*" = { script = "app/api/github/route" }
"/api/microcms*" = { script = "app/api/microcms/route" }