import type { Metadata } from "next";
// import { Noto_Sans_JP} from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleAnalytics } from "@next/third-parties/google";

const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-noto-sans-jp", 
});

export const metadata: Metadata = {
  title: "Masato's tech Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        {children}
      </body>
      {/* GoogleAnalyticsコンポーネントの追加 */}
      <GoogleAnalytics gaId={process.env.GA_ID ?? ""} />
    </html>
  );
}
